version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: 172.31.26.225 # isu-3 „ÅÆprivate ip
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  react:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - go
    links:
      - go
    environment:
      API: http://172.31.17.245:80
    ports:
      - "443:443"
